config:
  gcp:project: "your-staging-project-id"
  gcp:region: "us-central1"
  starter-gcp-messaging:bootstrapStackRef: "your-org/starter-gcp-bootstrap/staging"
  starter-gcp-messaging:enableRedis: "false"
  starter-gcp-messaging:redisTier: "BASIC"
  starter-gcp-messaging:redisMemorySizeGb: "1"
