config:
  gcp:project: "your-staging-project-id"
  gcp:region: "us-central1"
  starter-gcp-database:bootstrapStackRef: "organization/starter-gcp-bootstrap/staging"
  starter-gcp-database:dbTier: "db-custom-2-7680"
  starter-gcp-database:dbVersion: "POSTGRES_16"
  starter-gcp-database:dbAvailability: "REGIONAL"
  starter-gcp-database:dbPointInTime: "true"
