config:
  gcp:project: "your-prod-project-id"
  gcp:region: "us-central1"
  starter-gcp-secrets:bootstrapStackRef: "organization/starter-gcp-bootstrap/production"
  starter-gcp-secrets:databaseStackRef: "organization/starter-gcp-database/production"
