config:
  gcp:project: "your-staging-project-id"
  gcp:region: "us-central1"
  starter-gcp-secrets:bootstrapStackRef: "organization/starter-gcp-bootstrap/staging"
  starter-gcp-secrets:databaseStackRef: "organization/starter-gcp-database/staging"
